src/ServiceStack.Text/Common/WriteLists.cs, tests/ServiceStack.Text.Tests/EnumerableTests.cs, tests/ServiceStack.Text.Tests/ServiceStack.Text.Tests.csproj
Serializing something like `new ArrayList { 1, 1.2 }` would fail with the following:
```
System.InvalidCastException : Specified cast is not valid.
at ServiceStack.Text.Json.JsonTypeSerializer.WriteDouble(TextWriter writer, Object doubleValue)
at ServiceStack.Text.Common.WriteListsOfElements`1.WriteIEnumerable(TextWriter writer, Object oValueCollection)
at ServiceStack.Text.JsonSerializer.SerializeToString(T value)
```
=> Fixed IEnumerable's with mixed types.

src/ServiceStack.Text/Common/WriteDictionary.cs, src/ServiceStack.Text/Common/WriteType.cs, src/ServiceStack.Text/QueryStringSerializer.cs, tests/ServiceStack.Text.Tests/DictionaryTests.cs
When this manifests the serializer will begin
writing things like this:
"{\"foo\":123}"
instead of this:
{"foo":123}
=> Fixed possible corruption of thread local state.

src/ServiceStack.Text/Common/WriteLists.cs, tests/ServiceStack.Text.Tests/EnumerableTests.cs
* The issue here was even before previous change few weeks ago where presented only if the first item in collection was null.
* After the change it stopped working even if the first item in the collection was not null
* I didn't find a better way than using a default object serializer in such case
=> Fix null values serialization in ArrayList collection

src/ServiceStack.Text/Common/DeserializeTypeRefJson.cs, src/ServiceStack.Text/Common/DeserializeTypeRefJsv.cs, src/ServiceStack.Text/Common/JsDelegates.cs, src/ServiceStack.Text/JsConfig.cs, src/ServiceStack.Text/JsConfigScope.cs, tests/ServiceStack.Text.Tests/JsonTests/OnDeserializationErrorCallbackTest.cs, tests/ServiceStack.Text.Tests/JsonTests/ThrowOnDeserializeErrorTest.cs, tests/ServiceStack.Text.Tests/ServiceStack.Text.Tests.csproj
* Motivation:
* We would have more detailed error logging related to serialization issues so we can help to users better diagnose API level issues
* This change simply adds a generic hook for deserialization issues allowing to extend the parsed DTO with parsing errors as needed.
* I'm not sure about the change in ```DeserializeTypeRefJsv```: The pre-existing code there seems to slightly differ for second of the exception handler where ```DeserializeTypeRefJson``` uses ```typeAccessor.PropertyType```. The Jsv implementation seems to be incorrect therefor.
=> Invoke error handler callback for deserialization issues

src/ServiceStack.Text/Pcl.Dynamic.cs
Supporting properly parsing of arrays. Example:
```
var s = @"{ ""simple"": ""value"", ""obj"": { ""val"":""test"" }, ""array"": []";
var dyn = DynamicJson.Deserialize(s);
Console.WriteLine(dyn.simple);
Console.WriteLine(dyn.obj);
Console.WriteLine(dyn.obj.val);
Console.WriteLine(dyn.array);
```
=> Fixed DynamicsJson to parse arrays properly

src/ServiceStack.Text/HttpUtils.cs, tests/ServiceStack.Text.Tests/HttpUtilsTests.cs
The SetQueryParam method would search for the first occurrence of the param key string. And it would get a positive match even if the param key string was found inside a preceding parameters value.
=> Fixed SetQueryParam to set parameters correctly.

src/ServiceStack.Text/JsonObject.cs, tests/ServiceStack.Text.Tests/JsonTests/JsonObjectTests.cs
JSON specification does not allow to use numbers with leading zeros
see http://stackoverflow.com/questions/29048110/override-json-deserializing-a-number-with-a-leading-zero-as-a-decimal-and-not-an/29048193#29048193
for more information
=> Fix number with leading zeros serialization bug

src/ServiceStack.Text/Common/DeserializeTypeRefJson.cs, src/ServiceStack.Text/Common/DeserializeTypeRefJsv.cs, tests/ServiceStack.Text.Tests/JsonTests/PolymorphicInstanceTest.cs
* I found that when you specify __type in the JSON the deserializer at first activates the instance and then runs the type check
* To me this seems to be a security issue since you can basically activate any object remotely
* The class is immediately thrown away so no further code can be executed just what is inside the constructor
* I succesfully tested remote activation as well
=> Security fix: Explicitly specified __type should not be even activated when not appropriate

src/ServiceStack.Text/Json/JsonUtils.cs
Quote listed twice in escape chars.  Modulus 16 == bitwise AND 0xF.  Re-arrange logic to reduce code size and complexity.  Use char variable instead of index operation in various places.  Use constants instead of mixed constants and literals.  Comment some of the optimizations/oddities.  Dropped wasteful EscapeCharFlags in favor of two equality operations for the only two printable characters that require escaping (quote and backslash).  Removed now unused EscapeChars, now unused static constructor.  Created IsPrintable.  Suggestion for Linq-based alternative to HaveAnyEscapeChars and potential for loop unrolling.
=> Fixes, cleanups, and optimizations

README.md
www.servicestack.net/benchmarks results in a 404, changed to use the new http://mono.servicestack.net/benchmarks/ URL.
=> Fixes to benchmark links

src/ServiceStack.Text/HttpUtils.cs
Use Stopwatch instead of DateTime for boundary string creation (faster). Remove redundant array creation expressions (aka. "new[]").  Use fileStream.CopyTo (code reduction).  Remove assigned but not used local variable (strRes).
=> Boundary string speedup, minor fixes

src/ServiceStack.Text/Json/JsonUtils.cs, tests/ServiceStack.Text.Tests/JsonTests/EscapedCharsTests.cs
When deserializing this: "Hi I'm \r\n new line :)" produces:
"Hi I'm\
\
new line :)"
This occurs because a bug in JsonUtils.WriteString, on Escaped variables it's concating EscapedChar with the '\r', '\n', '\t'... Like this: { EscapeChar, CarriageReturnChar }, produces that bug.
SS:
=> Update string serialize with special chars.

src/ServiceStack.Text/Common/DeserializeListWithElements.cs, tests/ServiceStack.Text.Tests/JsonTests/JsonArrayObjectTests.cs
Allowing deserialization of object arrays when some of the objects are null but the first one is not null.
This worked:
```
{
"items": [
null,
{
"Item": "myitem"
}       
]
}
```
This threw a null reference exception
```
{
"items": [
{
"Item": "myitem"
},
null
]
}
```
=> json array containing nulls deserialization bug

src/ServiceStack.Text/Common/ITypeSerializer.cs, src/ServiceStack.Text/Common/WriteDictionary.cs, src/ServiceStack.Text/JsConfig.cs, src/ServiceStack.Text/JsConfigScope.cs, src/ServiceStack.Text/Json/JsonTypeSerializer.cs, src/ServiceStack.Text/Jsv/JsvTypeSerializer.cs, tests/ServiceStack.Text.Tests/DictionaryTests.cs
This is IMHO defect in JSON serialization since it actually skips null values.
There is a functional difference if you skip a null value for a property since that can be restored during the deserialization easily.
But if you ommit the key-value pair during the serialization the value is lost.
I am keeping the ability to skip null vaues in dictionaries though.
=> Dictionary should not skip null values even if null values should not be serialized

src/ServiceStack.Text/HttpUtils.cs, tests/ServiceStack.Text.Tests/HttpUtilsMockTests.cs
It was not possible to inspect the request body when mocking HTTP requests. As discussed here: http://stackoverflow.com/questions/31630526/can-i-test-form-data-using-httpresultsfilter-callback
This pull request fixes this. However, it does introduce breaking changes so I figure you may not wish to merge it as is.
=> Allow inspection of request body when mocking HTTP requests

src/ServiceStack.Text/Support/TimeSpanConverter.cs, tests/ServiceStack.Text.Tests/DateTimeOffsetAndTimeSpanTests.cs
unit tests for serialize/deserialize negative timespans
fix TimeSpanConverter to handle negative timespans
=> FixXsdTimeSpanSerializeDeserialize

src/ServiceStack.Text/Support/TimeSpanConverter.cs, tests/ServiceStack.Text.Tests/DateTimeOffsetAndTimeSpanTests.cs, tests/ServiceStack.Text.Tests/TimeSpanConverterTests.cs
one more fix to deserialization of negative timespan
moved unit tests added in previous pr to TimeSpanConvertTests, and added more tests there
=> FixXsdTimeSpanDeserialize

src/ServiceStack.Text/Common/DateTimeSerializer.cs
Serialization of DateTime using `DateHandler.ISO8601DateTime` incorrectly uses [hh](https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx#Anchor_20) instead of [HH](https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx#Anchor_22) which means hours in the PM would silently get converted to AM hours(!). In other words, no matter what you feed it, you'd always get an hour between 00 to 12 instead of 00 to 23.
PS as a side note, not sure a space is a valid character in ISO8601 representation between the date and the time (this should be a 'T') so I'm not sure about calling this ISO8601. It looks more like a MySQL DATETIME format.
=> Fix serialization bug in DateHandler.ISO8601DateTime (hh => HH)

src/ServiceStack.Text/HttpUtils.cs, tests/ServiceStack.Text.Tests/HttpUtilsTests.cs
before:
"http://example.com?".AddQueryParam("f", "1")  => "http://example.com?&f=1"
"http://example.com?f=1&".AddQueryParam("f", "2") => "http://example.com?f=1&&f=2"
after:
"http://example.com?".AddQueryParam("f", "1")  => "http://example.com?f=1"
"http://example.com?f=1&".AddQueryParam("f", "2") => "http://example.com?f=1&f=2"
=> fix handling urls endwith "&" or "?"

src/ServiceStack.Text/CsvConfig.cs, tests/ServiceStack.Text.Tests/CsvStreamTests.cs, tests/ServiceStack.Text.Tests/CsvTests/CustomHeaderTests.cs, tests/ServiceStack.Text.Tests/CsvTests/DictionaryTests.cs, tests/ServiceStack.Text.Tests/CsvTests/NewLineTests.cs
According to RFC 4180 https://www.ietf.org/rfc/rfc4180.txt CSV line must end with CRLF
Previous versions of CSV serializer generated CSV using Environment.NewLine
which differs on Windows/Linux/Mac platforms. This commit changes default CSV line ending to CRLF and fixes the tests for Linux/Mac platform.
=> Fix CSV tests on Linux

src/ServiceStack.Text/Common/DeserializeType.cs, tests/ServiceStack.Text.Tests/JsonTests/InheritanceTests.cs, tests/ServiceStack.Text.Tests/ServiceStack.Text.Tests.csproj
Fixes https://github.com/ServiceStack/Issues/issues/451#issuecomment-230575637
extension PropertyInfo.ReflectedType() in PCL version returns `MemberInfo.DeclaringType` instead of  `MemberInfo.ReflectedType`, because `MemberInfo.ReflectedType` is not available in PCL profile. `TypeConfig` contains information about deserialized type and it's the same as `PropertyInfo.ReflectedType`.
=> Fix PCL deserializing private set property in base type

src/ServiceStack.Text/PclExport.Net40.cs, src/ServiceStack.Text/PclExport.NetStandard.cs, src/ServiceStack.Text/PclExport.cs, src/ServiceStack.Text/ReflectionExtensions.cs
Most of HttpWebRequest properties are not implemented on .NET Core,
but they are exist on other platforms such as Xamarin and .NET, so we can try to find the properties by Reflection and call setter on them, if property does not exists just do usual way
=> Add ability to set up HttpWebRequest properties

src/ServiceStack.Text/JsonObject.cs
I added an overloaded non-generic ConvertTo function to the JsonObject class which takes in a Type object and made the generic function use this new function to keep the code in one place. 
I need to use this class without knowing the type during the first deserialization forcing the use of reflection to call this function with the type object. Currently I am creating an object which inherits your JsonObject and putting the function there which is adequate, but wanted to see if you thought this was worth putting in your object as well for others.
=> JsonObject helper class missing non-generic ConvertTo function overload

src/ServiceStack.Text/TextExtensions.cs, tests/ServiceStack.Text.Tests/CsvTests/ObjectSerializerTests.cs
Unlike JsonSerializer, CsvSerializer does not utilise TypeSerializer and therefore does not support custom serialization.
This PR implements this support with a relatively simple change to the ToCsvField extension method.
=> Custom serialization support for CsvSerializer

src/ServiceStack.Text/TextExtensions.cs, tests/ServiceStack.Text.Tests/CsvSerializerTests.cs, tests/ServiceStack.Text.Tests/JsonTests/RouteValueDictionaryTests.cs
Csv serialisation of collection of Dictionary or Dynamic types with empty string generates index out of range exception.
=> Fix for dictionary object with empty string

src/ServiceStack.Text/Common/DateTimeSerializer.cs, tests/ServiceStack.Text.Tests/JsonTests/JsonDateTimeTests.cs
**DateTime** handling is inconsistent with respect to the `AssumcUtc` when using the `JSConfig` setting.
If serializing to **JSON** - The `JsonTypeSerializer` will use the **UTC** specification type and convert `Unspecified` **DateTime** values to **UTC** in method `WriteWcfJsonDate`
If serializing to **CSV**- The `JsvTypeSerializer` will not use the **UTC** specification type and does not convert `Unspecified` **DateTime** values to **UTC** in method `ToShortestXsdDateTimeString`
Adding an internal extension method `UseConfigSpecifiedSetting` to match **DateTime** conversion between the two different serializers.
=> JsonSerializer/JsvTypeSerializer inconsistently uses the AssumeUtc config setting

src/ServiceStack.Text/Common/DeserializeType.cs, tests/ServiceStack.Text.Tests/ReportedIssues.cs
Child classes marked as DataContract inheriting protected DataMember fields and properties causes a NullReferenceException to be thrown on deserialization.
I stumbled upon this issue on accident when I mistakenly applied the DataMember property to a protected property of a parent class. This mistake unfortunately caused a NullReferenceException which was not easy to diagnose since I assumed the problem must have been in some other logic since I never intended to serialize the property the first place.
The change of the binding flags is just one possible way to alleviate the problem. Looks to be possible to return null from GetSetPropertyMethod, but I did not look further into GetSetFieldMethod to see if returning null was possible there. There are probably other ways to solve the problem, …
=> A data contract class with inherited non-public data members causes an NRE on deserialization

src/ServiceStack.Text/Common/DateTimeSerializer.cs, src/ServiceStack.Text/JsConfig.cs, src/ServiceStack.Text/JsConfigScope.cs, tests/ServiceStack.Text.Tests/CsvTests/ObjectSerializerTests.cs
JSON and XML both show a datetime with the fractional seconds like so
`2018-02-10T00:00:00.0000000Z`
but CSV will produce a DateTime with out the any of the timespan portion of timezone indicator i.e.
`2018-01-01`
this is also not consistent with the default ISO8601 parser in .NET for DateTime called as so `.ToString("o")` will produce the ISO8601 serialized times as for JSON and XML, but not CSV.
Adding the ability to specify a DateTimeFormat that will allow a user to override the DateTimeFormat defaults so serialized value is consistent.
Using the `JsConfig<DateTime>.SerializeFn` is a way for me to personally fix this, but point 1 I would then be overriding default behavior for all serialization types because I want them to be consistent in how they write serialized values which I think …
=> DateTimes that are exported in ISO8601 are not consistent across serialization formats JSON/XML/CSV

src/ServiceStack.Text/PlatformExtensions.cs, tests/ServiceStack.Text.Tests/AutoMappingObjectDictionaryTests.cs
We're working on a Neo4j User Auth Repository but their low-level [driver](https://github.com/neo4j/neo4j-dotnet-driver) is a little tricky to handle deserialization via IRecord. The FromObjectDictionary method (I think) will work nicely if it can support interfaces.
=> Support IReadOnlyDictionary in FromObjectDictionary

src/ServiceStack.Text/Support/TimeSpanConverter.cs, tests/ServiceStack.Text.Tests/TimeSpanConverterTests.cs
Hi
My pull request first show culture depended problem in converting TimeSpan to XsdDuration string and from string. In last commit I'm suggesting the solution.
1. By default tests: **Can_Serialize_TimeSpan** and **Can_deserialize_TimeSpan** failed on my computer because I use different culture so I have corrected this two tests to replicate good result on my computer: 
https://github.com/ServiceStack/ServiceStack.Text/commit/a16175af3ecf85015cf84ebefdd8fede4650284a
2. In https://github.com/ServiceStack/ServiceStack.Text/commit/4d009f82cf487c420a354867d5bc07f8d6480c34 I have add another two tests with using my culture to replicate problem on your computers.
3. In 
https://github.com/ServiceStack/ServiceStack.Text/commit/47a7f57b12af7dc47b807623e8af95d9994cb4cd I'm suggesting the solution …
=> Time span converter culture

src/ServiceStack.Text/Common/DeserializeDictionary.cs, src/ServiceStack.Text/Common/JsWriter.cs, tests/ServiceStack.Text.Tests/JsonObjectTests.cs
For a project that creates a type which inherits from ServiceStack.Text's JsonObject, the inherited object is treated differently than the base object because of hard-coded equality comparisons. 
This PR allows projects to create inherited JsonObject types which perform identically to the JsonObject base class.
This PR could replace the existing code in the DeserializeDictionary class, but I just added my changes to minimize impact.
I have verified that this PR fixes the issue in my project, but I did not add a unit test because of the complication in replicating it generically outside my project. Let me know if you have any questions.
=> Added support for inherited JsonObject types.

src/ServiceStack.Text/PlatformExtensions.cs, src/ServiceStack.Text/TranslateListWithElements.cs, tests/ServiceStack.Text.Tests/AutoMappingObjectDictionaryTests.cs, tests/ServiceStack.Text.Tests/AutoMappingTests.cs
Disclosure: I'm working on [Neo4jMapper](https://github.com/neildobson-au/Neo4jMapper) which uses ServiceStack.Text to read data from Neo4j using their low-level [driver](https://github.com/neo4j/neo4j-dotnet-driver) and convert to POCOs. However due to the nature of graph databases, the data structures are complex, and the return types have nested dictionaries.
=>  Support nested dictionaries in FromObjectDictionary through recursion 

src/ServiceStack.Text/Jsv/JsvTypeSerializer.cs
This PR fixes a minor bug in JsvTypeSerializer which leads to a StackOverflow exception due an infinite recursive call.
=> Fixed erroneous recursive call in JsvTypeSerializer.EatMapStartChar

tests/ServiceStack.Text.Tests/JsonTests/LowercaseUnderscoreTests.cs
Hey @mythz ,
Spotted an issue with `TypeAccessorUtils.Get` (i think, see failing test) where if a JsConfig scope is set to lenient a datamember name of snake case will be missed. Previously this would work on 5.0.2 and I think 5.1 . 
I tried a fix but this looks like a pretty hot path that was refactored for performance gains, I can't see another way without testing both original and lenient property names which would require an additional string allocation and potential double up on the binary search. 
Thoughts?
=> Issue using lenient scope with DataMember Name and SnakeCase.

tests/ServiceStack.Text.Tests/Support/MovieDtos.cs
CsvSerializerTests fail with the newly added test data entries.
After SerializeAndDeserialize, `"Mr. Lee"` becomes `Mr. Lee` and `"Anon" Review` becomes `Anon" Revie`
=> Bug Report: CsvSerializer doesn't handle strings that start with double quotes properly.

src/ServiceStack.Text/CsvReader.cs, tests/ServiceStack.Text.Tests/CsvTests/ObjectSerializerTests.cs
Fixing issue where `List<string> values` couldn't go `ToCsv()` and back `FromCsv<List<string>>()` consistently.
Eg,
```csharp
var list = new List<string>
{
"one",
"two",
"three"
};
var flatList = list.ToCsv();
var originalList = flatList.FromCsv<List<string>>();
```
Where `originalList` would have a 1 element rather than 3 elements like the original input.
=> Fix List primitive to/from CSV so that same input gets the same output.

src/ServiceStack.Text/HttpUtils.cs
I've noticed that uppercase extensions of binary files are treated as text. I've encountered that in the ServiceStack.Aws project.
The result was that files named like IMG_123**.JPG** were returning different content lengths when renamed to IMG_123**.jpg** (on S3)
=> Support uppercase file extentions

src/ServiceStack.Text/Json/JsonReader.Generic.cs, src/ServiceStack.Text/Json/JsonWriter.Generic.cs, src/ServiceStack.Text/Jsv/JsvReader.Generic.cs, src/ServiceStack.Text/Jsv/JsvWriter.Generic.cs, tests/ServiceStack.Text.Tests/Issues/JsConfigIssues.cs
See https://forums.servicestack.net/t/jsconfig-reset-inconsistencies/9957
=> Fix issue where DeserializeFn is not cleared by reset
